//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tra_Verse.Models
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class TraVerseEntities : DbContext
    {
        public TraVerseEntities()
            : base("name=TraVerseEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VacationLog> VacationLogs { get; set; }
    }
}
