//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tra_Verse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacationLog
    {
        public int OrderID { get; set; }
        public string PlanetName { get; set; }
        public int Price { get; set; }
        public double Rating { get; set; }
        public string DateStart { get; set; }
        public string DateEnd { get; set; }
        public string ShipType { get; set; }
        public string CompanyName { get; set; }
        public string PlanetImage { get; set; }
        public string Refundable { get; set; }
        public string Exosuit { get; set; }
    }
}
